blank_issues_enabled: true
contact_links:
  - name: Contact me on Discord
    url: https://discord.com/users/289142457218891777
  - name: "#souls-dev in my Discord Server"
    url: https://discord.gg/Kkb5MSqy7x
  - name: Twitch
    url: https://twitch.tv/sovietspaceship
  - name: "#research in Elden Ring PvP"
    url: https://discord.gg/vb2uWpmXhc