blank_issues_enabled: true
contact_links:
  - name: Contact me
    url: https://discord.com/users/289142457218891777
    about: Discord
  - name: "Discord Server"
    url: https://discord.gg/Kkb5MSqy7x
    about: "Check out #souls-dev"
  - name: Twitch
    url: https://twitch.tv/sovietspaceship
    about: My Twitch channel
  - name: "Elden Ring PvP"
    url: https://discord.gg/vb2uWpmXhc
    about: "Ping me in #research"