name: Dark Souls III Inventory Tool Feature Request Form
description: Request a feature for Dark Souls III Inventory Tool
title: '[Dark Souls III Inventory Tool] PLEASE_INSERT_ISSUE_TITLE_HERE'
labels: 
  - ds3_inventory
  - enhancement
assignees: 
  - sovietspaceship
body:
  - type: markdown
    attributes:
      value: |
        **Application**: Dark Souls III Inventory Tool (https://ds3-inventory.nyasu.business)
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      placeholder: "A clear and concise description of what you want to happen."
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      placeholder: "A clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Any additional context, screenshots, examples or mock-ups about the requested feature."
