name: Dark Souls III Inventory Tool Incorrect Data Report Form
description: Report incorrect data in Dark Souls III Inventory Tool
title: '[Dark Souls III Inventory Tool] PLEASE_INSERT_ISSUE_TITLE_HERE'
labels: 
  - ds3_inventory
  - data
assignees: 
  - sovietspaceship
body:
  - type: markdown
    attributes:
      value: |
        **Application**: Dark Souls III Inventory Tool (https://ds3-inventory.nyasu.business)
  - type: textarea
    attributes:
      label: Describe the incorrect or missing data
      placeholder: "A clear and concise description of what the bug is. Link any sources such as wikis or datamines."
  - type: textarea
    attributes:
      label: Evidence
      placeholder: "Screenshots or details from game data or other supporting tools."
  - type: input
    attributes:
      label: Build or workspace URL
      description: "If applicable, provide the URL of your build or workspace that displays the issue."
      placeholder: "https://..."
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Add any other context about the problem here."
