name: Elden Ring Build & Inventory Planner Incorrect Data Report Form
description: Report incorrect data in Elden Ring Build & Inventory Planner
title: '[Elden Ring Build & Inventory Planner] PLEASE_INSERT_ISSUE_TITLE_HERE'
labels: 
  - er build planner
  - data
assignees: 
  - sovietspaceship
body:
  - type: markdown
    attributes:
      value: |
        **Application**: Elden Ring Build & Inventory Planner (https://er-build-planner.nyasu.business)
  - type: textarea
    attributes:
      label: Describe the incorrect or missing data
      placeholder: "A clear and concise description of what the bug is. Link any sources such as wikis or datamines."
  - type: textarea
    attributes:
      label: Evidence
      placeholder: "Screenshots or details from game data or other supporting tools."
  - type: input
    attributes:
      label: Build or workspace URL
      description: "If applicable, provide the URL of your build or workspace that displays the issue."
      placeholder: "https://..."
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Add any other context about the problem here."
