name: Elden Ring Build & Inventory Planner Bug Report
description: Report an issue with Elden Ring Build & Inventory Planner
title: '[Elden Ring Build & Inventory Planner] PLEASE_INSERT_ISSUE_TITLE_HERE'
labels: 
  - er build planner
  - bug
assignees: 
  - sovietspaceship
body:
  - type: markdown
    attributes:
      value: |
        **Application**
  - type: input
    id: app_title
    attributes:
      label: Application Title
      description: "Enter the title of the application (Elden Ring Build & Inventory Planner)."
      placeholder: "Elden Ring Build & Inventory Planner"
      value: Elden Ring Build & Inventory Planner
  - type: input
    id: app_url
    attributes:
      label: Application URL
      description: "Provide the URL of the application (https://er-build-planner.nyasu.business)."
      placeholder: "https://er-build-planner.nyasu.business"
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is. If possible, also include the date and time the bug happened."
      placeholder: "A clear and concise description of the bug."
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: "A clear and concise description of what you expected to happen."
  - type: input
    id: build_or_workspace_url
    attributes:
      label: Build or workspace URL
      description: "If applicable, provide the URL of your build or workspace that displays the issue."
      placeholder: "URL of the build or workspace."
      optional: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Add screenshots here."
      render: file
      optional: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: "Specify whether you are using a desktop or mobile device."
      options:
        - Desktop
        - Mobile
  - type: input
    id: browser
    attributes:
      label: Browser
      description: "Specify the browser you are using."
      placeholder: "e.g., Chrome, Firefox, Safari"
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
      placeholder: "Any additional context about the problem."
      optional: true
  - type: markdown
    attributes:
      value: |
        **Before you submit**

        Please try the following:

        - If user interface issue: Press F12 -> Right click on Reload button -> Empty cache and hard reload
        - If issue in conjunction with external software, such as TGA's cheat table: Make sure you are using the latest version of the software or table
