name: Elden Ring Frame Data Explorer Incorrect Data Report Form
description: Report incorrect data in Elden Ring Frame Data Explorer
title: '[Elden Ring Frame Data Explorer] PLEASE_INSERT_ISSUE_TITLE_HERE'
labels: 
  - er framedata
  - data
assignees: 
  - sovietspaceship
body:
  - type: markdown
    attributes:
      value: |
        **Application**: Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)
  - type: textarea
    attributes:
      label: Describe the incorrect or missing data
      placeholder: "A clear and concise description of what the bug is. Link any sources such as wikis or datamines."
  - type: textarea
    attributes:
      label: Evidence
      placeholder: "Screenshots or details from game data or other supporting tools."
  - type: input
    attributes:
      label: Build or workspace URL
      description: "If applicable, provide the URL of your build or workspace that displays the issue."
      placeholder: "https://..."
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Add any other context about the problem here."
