name: Elden Ring Frame Data Explorer Bug Report Form
description: Report an issue with Elden Ring Frame Data Explorer
title: '[Elden Ring Frame Data Explorer] PLEASE_INSERT_ISSUE_TITLE_HERE'
labels: 
  - er framedata
  - bug
assignees: 
  - sovietspaceship
body:
  - type: markdown
    attributes:
      value: |
        **Application**: Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)
  - type: textarea
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is. If possible, also include the date and time the bug happened."
      placeholder: "A clear and concise description of what the bug is."
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: "A clear and concise description of what you expected to happen."
  - type: input
    attributes:
      label: Build or workspace URL
      description: "If applicable, provide the URL of your build or workspace that displays the issue."
      placeholder: "https://..."
  - type: textarea
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Add screenshots here."
  - type: dropdown
    attributes:
      label: Device
      description: "Specify whether you are using a desktop or mobile device."
      options:
        - Desktop
        - Mobile
        - Mobile (Installed)
  - type: input
    attributes:
      label: Browser
      description: "Specify the browser you are using, optionally including version."
      placeholder: "e.g., Chrome, Firefox, Safari"
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Any additional context about the problem."
  - type: markdown
    attributes:
      value: |
        **Before you submit**

        Please try the following:

        - If user interface issue:
          * Press F12 -> Right click on Reload button -> Empty cache and hard reload
        - If issue in conjunction with external software, such as TGA's cheat table:
          * Make sure you are using the latest version of the software or table
