name: Elden Ring Frame Data Explorer Feature Request Form
description: Request a feature for Elden Ring Frame Data Explorer
title: '[Elden Ring Frame Data Explorer] PLEASE_INSERT_ISSUE_TITLE_HERE'
labels: 
  - er_framedata
  - enhancement
assignees: 
  - sovietspaceship
body:
  - type: markdown
    attributes:
      value: |
        **Application**: Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      placeholder: "A clear and concise description of what you want to happen."
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      placeholder: "A clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Any additional context, screenshots, examples or mock-ups about the requested feature."
